# Site settings
title: Aliança pela Água
description: Preocupado com a falta de água? Junte-se a nós para apresentar propostas efetivas e exigir transparência na divulgação de informações pelo governo
analytics_id: UA-720697-34
email: cadastro_online@socioambiental.org
facebook: 303397239864996
twitter: teste
gplus: teste
youtube: teste
twitter_share: "Campanha Água@SP mapeia atores e propostas para o enfrentamento da crise em São Paulo: #AguaSP"

collections:
- apresentacao
- quem

# Build settings
markdown: kramdown

gems: [jekyll-sass]
