# Site settings
title: Aliança pela Água
description: 
analytics_id: UA-720697-34
email: tester@test.com
facebook: 303397239864996
twitter: teste
gplus: teste
youtube: teste

collections:
- apresentacao
- quem

# Build settings
markdown: kramdown

gems: [jekyll-sass]
