# Site settings
title: Aliança pela Água
description: O vento balança os coqueiros que moram (dançam) na beira do mar!
analytics_id: UA-XXXXX-X
email: tester@test.com
facebook: 303397239864996
twitter: teste
gplus: teste
youtube: teste

collections:
- apresentacao
- quem

# Build settings
markdown: kramdown

gems: [jekyll-sass]
